action_mailer:
  perform_deliveries: true
  delivery_method: file
  raise_delivery_errors: false
  smtp_server: smtp.psu.edu
  smtp_port: 25

default_url_options:
  host: metadata.test
  protocol: http

external_assets:
  endpoint: https://assets.uldev.k8s.libraries.psu.edu
